---
title: "Project 1"
author: "Alden Swain"
date: "2023-10-05"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(MASS)
library(ggplot2)
library(tidyverse)
```

```{r}
# Read data in
diamonds = read.csv("diamonds4.csv")

# Refactor the variables to be in categorical order
diamonds$cut <- factor(diamonds$cut, levels=c('Astor Ideal', 'Ideal', 'Very Good', 'Good'))
diamonds$clarity <-factor(diamonds$clarity, levels=c('FL', 'IF', 'VVS1', 'VVS2', 'VS1', 'VS2', 'SI1', 'SI2')) 
diamonds$color <- factor(diamonds$color, levels=c('D', 'E', 'F', 'G', 'H', 'I', 'J'))

# Graph for carat effect on price
ggplot(diamonds, aes(x=carat, y=price)) + 
geom_point() + 
geom_smooth(method="lm", se=FALSE) + 
labs(x="Carat", y="Price", title="Carat Effect on Price") + 
theme(plot.title=element_text(hjust=0.5), 
      axis.title.x = element_text(size = 15),
      axis.title.y = element_text(size = 15),
      title = element_text(size = 15))


# Color effect on price
ggplot(diamonds, aes(x=color, y=price)) + 
geom_violin() + 
labs(x="Color", y="Price", title="Color Effect on Price") + 
theme(plot.title=element_text(hjust=0.5), 
      axis.title.x = element_text(size = 15),
      axis.title.y = element_text(size = 15),
      title = element_text(size = 15))


ggplot(diamonds, aes(x=carat, y=price, color=color)) + 
geom_point() + 
labs(x="Carat", y="Price", title="Carat and Color Effect on Price", color = "Color") + theme(plot.title=element_text(hjust=0.5), 
      axis.title.x = element_text(size = 15),
      axis.title.y = element_text(size = 15),
      title = element_text(size = 15))



ggplot(diamonds, aes(x=carat, y=price, col=color)) + 
geom_smooth(se=F) + 
labs(title = 'Price by Carat and Color', x = "Carat", y = "Price", color = "Color")+ 
theme(plot.title=element_text(hjust=0.5), 
      axis.title.x = element_text(size = 15),
      axis.title.y = element_text(size = 15),
      title = element_text(size = 15))







ggplot(diamonds, aes(x=clarity, y=price)) + 
geom_violin() + 
labs(x="Clarity", y="Price", title="Clarity Effect on Price") + 
theme(plot.title=element_text(hjust=0.5), 
      axis.title.x = element_text(size = 15),
      axis.title.y = element_text(size = 15),
      title = element_text(size = 15))


newdiamonds <- diamonds %>%
  group_by(clarity) %>%
  summarize(Count = n())

ggplot(newdiamonds, aes(x = clarity, y = Count)) + 
geom_col() + 
labs(title="Number of Diamonds by Clarity", x = "Clarity", y = "Count")+ 
  geom_text(aes(label = Count, y = Count+10)) +
theme(plot.title=element_text(hjust=0.5), 
      axis.title.x = element_text(size = 15),
      axis.title.y = element_text(size = 15),
      title = element_text(size = 15))





ggplot(diamonds, aes(x=carat, y=price, col=clarity)) +
geom_smooth(se=F) +
labs(title ='Price by Carat and Clarity', x ="Carat", color = "Clarity", y= "Price") +
theme(plot.title=element_text(hjust=0.5), 
      axis.title.x = element_text(size = 15),
      axis.title.y = element_text(size = 15),
      title = element_text(size = 15))


ggplot(diamonds, aes(x=cut, y=price)) + 
geom_violin() + 
labs(x="Cut", y="Price", title="Cut Effect on Price") + 
theme(plot.title=element_text(hjust=0.5), 
      axis.title.x = element_text(size = 15),
      axis.title.y = element_text(size = 15),
      title = element_text(size = 15))

ggplot(diamonds, aes(x=clarity, fill=color)) + 
geom_bar(position="fill") + 
labs(x="Clarity", y="Proportion", title="Dist of Clarity and Color by Cut") + 
facet_wrap(~cut) + 
scale_fill_brewer(palette = "Paired") + 
theme(plot.title=element_text(hjust=0.5), 
      axis.title.x = element_text(size = 15),
      axis.title.y = element_text(size = 15),
      title = element_text(size = 15),
      axis.text.x = element_text(angle = 30))





newdiamonds2 <- diamonds %>%
  group_by(cut) %>%
  summarize(Count = n())

ggplot(newdiamonds2, aes(x = cut, y = Count)) + 
geom_col() + 
labs(title="Number of Diamonds by Cut", x = "Cut", y = "Count")+ 
  geom_text(aes(label = Count, y = Count+20)) +
theme(plot.title=element_text(hjust=0.5), 
      axis.title.x = element_text(size = 15),
      axis.title.y = element_text(size = 15),
      title = element_text(size = 15))


ggplot(diamonds, aes(x=carat, y=price, color=cut)) + 
  geom_point() + 
  labs(x="Carat", y="Price", title="Carat and Cut Effect on Price", color = "Cut") + 
  theme(plot.title=element_text(hjust=0.5), 
      axis.title.x = element_text(size = 15),
      axis.title.y = element_text(size = 15),
      title = element_text(size = 15)) +
  scale_color_manual(values = c("Astor Ideal" = "violet", "Ideal" = "blue", "Very Good" = "green", "Good" = "maroon"))



ggplot(diamonds, aes(x=color, fill=clarity)) + 
  geom_bar(position = "fill") + 
  labs(x="Color", y="Proportion",fill = "Clarity", title="Relating Clarity to Color") +   theme(plot.title=element_text(hjust=0.5), 
      axis.title.x = element_text(size = 15),
      axis.title.y = element_text(size = 15),
      title = element_text(size = 15))




ggplot(diamonds, aes(x=carat, y=price, color=clarity)) + 
  geom_point() + 
  labs(x="Carat", y="Price", color = "Clarity", title="Carat and Clarity Effect on Price") + theme(plot.title=element_text(hjust=0.5), 
      axis.title.x = element_text(size = 15),
      axis.title.y = element_text(size = 15),
      title = element_text(size = 15)) + scale_color_manual(values = c("FL" = "gray", "IF" = "red", "VVS1" = "green", "VVS2" = "green", "VS1" = "blue", "VS2" = "blue", "SI1" = "orange", "SI2" = "orange"))



ggplot(diamonds, aes(x=carat, y=price)) + 
geom_point() + 
geom_smooth(se = F) + 
labs(title = 'Carat Effect on Price', x = "Carat", y = "Price") +
  theme(plot.title=element_text(hjust=0.5), 
      axis.title.x = element_text(size = 15),
      axis.title.y = element_text(size = 15),
      title = element_text(size = 15)) 

reg_standard <- lm(price~carat, data = diamonds) 
par(mfrow=c(2, 2)) 
plot(reg_standard, which = 1)






boxcox(reg_standard,  lambda = seq(-1, 1, .1))


log_price <- lm(log(price)~carat, data = diamonds) 
plot(log_price, which = 1)

 
ggplot(diamonds, aes(x=carat, y=log(price))) + 
geom_point() + 
geom_smooth(method = 'lm',se = F) + 
labs(title = 'Carat Effect on log(Price)',
     x = "Carat",
     y = "log(Price)")+
  theme(plot.title=element_text(hjust=0.5), 
      axis.title.x = element_text(size = 15),
      axis.title.y = element_text(size = 15),
      title = element_text(size = 15)) 




ggplot(diamonds, aes(x=log(carat), y=log(price))) + 
geom_point() + 
geom_smooth(method = 'lm',se = F) + 
labs(title = 'log(Carat) Effect on log(Price)', x = "log(Carat)", y = "log(Price") +
    theme(plot.title=element_text(hjust=0.5), 
      axis.title.x = element_text(size = 15),
      axis.title.y = element_text(size = 15),
      title = element_text(size = 15)) 


reg <- lm(log(price)~log(carat), data = diamonds)
par(mfrow=c(2, 2)) 
plot(reg)


acf(reg$residuals, main="ACF Plot of Residuals with Y*")


```

